ALTER TABLE airports ALTER COLUMN ident DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN type DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN continent DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN iso_country DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN iso_region DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN municipality DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN scheduled_service DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN gps_code DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN iata_code DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN local_code DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN home_link DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN wikipedia_link DROP DEFAULT;
ALTER TABLE airports ALTER COLUMN name DROP DEFAULT;

ALTER TABLE countries ALTER COLUMN code DROP DEFAULT;
ALTER TABLE countries ALTER COLUMN name DROP DEFAULT;
ALTER TABLE countries ALTER COLUMN contintent DROP DEFAULT;
ALTER TABLE countries ALTER COLUMN wikipedia_link DROP DEFAULT;
ALTER TABLE countries ALTER COLUMN keywords DROP DEFAULT;

ALTER TABLE regions ALTER COLUMN code DROP DEFAULT;
ALTER TABLE regions ALTER COLUMN local_code DROP DEFAULT;
ALTER TABLE regions ALTER COLUMN name DROP DEFAULT;
ALTER TABLE regions ALTER COLUMN continent DROP DEFAULT;
ALTER TABLE regions ALTER COLUMN iso_country DROP DEFAULT;
ALTER TABLE regions ALTER COLUMN wikipedia_link DROP DEFAULT;
ALTER TABLE regions ALTER COLUMN keywords DROP DEFAULT;